import { join } from "node:path";
import type { Plugin } from "vite";
import type { ResolvedShironesPaths } from "./types.ts";

/**
 * Resolve bare specifiers that only exist inside the theme package.
 *
 * Under pnpm's strict `node_modules` layout, the theme's own dependencies are
 * not visible from the user's project root. Most imports are fine because
 * their importer lives inside the package, so Vite walks up from there — but
 * some are requested from contexts anchored at the project root:
 *
 *   - `virtual:astro:renderers`, generated by Astro, imports
 *     `@astrojs/svelte/server.js`
 *   - injected route entrypoints resolved before their importer is known
 *
 * Those fail with "failed to resolve import … from virtual:astro:renderers".
 *
 * Rather than pushing a pile of implementation-detail packages onto the user's
 * dependency list, this plugin retries any failed bare specifier using a file
 * inside the package as the importer, which makes Vite search the package's
 * own `node_modules`. Vite does the resolving, so `exports` maps and ESM-only
 * packages behave exactly as they should.
 */
export function shironesFallbackResolver(paths: ResolvedShironesPaths): Plugin {
	// Any real path inside the package works as a resolution anchor: Vite walks
	// up from its directory looking for `node_modules`.
	const anchor = join(paths.packageRoot, "package.json");
	const rescued = new Map<string, string>();

	return {
		name: "shirones:fallback-resolver",
		// Runs after Vite's own resolver so we only see genuine failures.
		enforce: "post",

		async resolveId(source, importer, options) {
			// Only bare specifiers can miss because of the node_modules layout.
			if (/^[./]/.test(source)) return null;
			if (source.startsWith("\0")) return null;
			if (source.includes(":")) return null; // virtual:, astro:, node:, data:

			// Guard against re-entering through our own `this.resolve` calls.
			if (options?.custom?.["shirones:fallback"]) return null;
			const custom = { ...options?.custom, "shirones:fallback": true };

			const direct = await this.resolve(source, importer, {
				...options,
				skipSelf: true,
				custom,
			});
			// Resolvable as-is: stay out of the way.
			if (direct) return null;

			const fallback = await this.resolve(source, anchor, {
				...options,
				skipSelf: true,
				custom,
			});
			if (!fallback) return null;

			if (!rescued.has(source)) {
				rescued.set(source, fallback.id);
			}
			return fallback;
		},

		buildEnd() {
			if (rescued.size === 0) return;
			const names = [...rescued.keys()].sort().join(", ");
			this.info?.(`resolved from the theme package: ${names}`);
		},
	};
}
